# See https://wiki.hypr.land/Configuring/Basics/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

# Optimized for retina-class 2x displays, like 13" 2.8K, 27" 5K, 32" 6K.
env = GDK_SCALE,1
monitor = desc:LG Electronics LG ULTRAGEAR 302NTVS7C639, 2560x1440, 0x0, 1
monitor = DP-1, 3440x1440, 2560x0, 1
monitor = eDP-2, preferred, 6000x0, 1.6

workspace = 1, monitor:DP-1, default:true
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:desc:LG Electronics LG ULTRAGEAR 302NTVS7C639
workspace = 5, monitor:eDP-2
